name: Update System Architecture SVG on README Change
permissions:
  contents: write
on:
  push:
    paths:
      - 'README.md'

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install graphviz wget
        python -m pip install --upgrade pip
        pip install graphviz markdown_to_json

    - name: Run the Python script
      run: |
        wget https://raw.githubusercontent.com/queens-autodrive/diagram_generator/main/graph.py
        python3 graph.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add system_architecture.svg
        git commit -m "Update System Architecture Diagram"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
